Blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from Blog import settings
from myBlog import views
from django.views import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),  # 网站首页
    path('list-<int:lid>.html', views.list, name='list'),  # 列表页
    path('show-<int:sid>.html', views.show, name='show'),  # 内容页
    path('tag/<tag>', views.tag, name='tags'),  # 标签列表页
    path('s/', views.search, name='search'),  # 搜索列表页
    path('about/', views.about, name='about'),  # 联系我们单页
    path('accounts/', include('allauth.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('deletecomment/', include('comment.deleteUrls', namespace='deletecomment')),
    path('404/', views.page_not_found, name='404'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

templates/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-dns-prefetch-control" content="on"/>
    <meta http-equiv="X-UA-Compatible" content="IE=11,IE=10,IE=9,IE=8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-title" content="Simon's Blog">
    <title>Simon's Blog</title>
    <link rel="icon" type="image/x-icon" href="{% static "images/favicon.ico" %}" />
    <link rel='stylesheet' id='bootstrap-css' href='{% static "css/bootstrap.min.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' id='fontawesome-css' href='{% static "css/font-awesome.min.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' id='stylesheet-css' href='{% static "css/style.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' id='raxus-css' href='{% static "css/raxus.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' id='open-social-style-css' href='{% static "css/os.css" %}' type='text/css' media='all'/>
    <link rel="stylesheet" href="{% static "live2d/css/live2d.css" %}"/>
    <link rel="stylesheet" href="{% static "css/back-top.css" %}"/>
    <meta name='robots' content='index,follow'/>
    <meta name="keywords" content="自用，闲来无事做的">
    <meta name="description" content="一个小白的网站，希望一起提高，共勉">


</head>
<body class="home blog site-layout-2" style="display: flex; flex-direction: column; background: #ecebe6">



<!-- 头部 -->
<header class="fix-wrap" id="fix-wrap">
    <div class="fix-main clearfix pr" id="fix-main" _hover-ignore="1"><a href="/" class="index-logo">
        <img src="{% static "picture/black-logo.png" %}" alt="拓普Python学院,Python!"></a>
        <nav class="nav fl">
            <ul id="fix-list" class="fix-list clearfix">

                <li id="menu-item-24086" class="menu-item"><a href="/">首页</a></li>
                    {% for category in allcategory %}
                        <li id="menu-item-117720" class="menu-item">
                            <a href="{% url 'index' %}list-{{ category.id }}.html">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                <li id="menu-item-24086" class="menu-item"><a href="/about/">关于博主</a></li>
            </ul>
        </nav>
        <form method="get" class="index-search  hidden-xs"  action="{% url 'index' %}s/">
            <label for="searchSth"></label><input class="searchBar" name="search" id ="searchSth" type="text" placeholder="输入关键字" value="">
            <button class="btn" style="color: darkslategrey" type="submit"><i class="fa fa-search"></i></button>
        </form>

    </div>

</header>

<div class="content" style="flex:1 0 auto ">
    {% block content %}

    {% endblock %}
</div>

<p id="back-top" style="display:none"><a href="#top"><span></span></a></p>


<!-- 底部 -->
<div id="landlord">
    <div class="message" style="opacity:0"></div>
    <canvas id="live2d" width="280" height="350" class="live2d"></canvas>
</div>
<footer class="footer" style="flex-shrink: 0">
    <div class="copyright"> © 2020- 2020 · All Rights Reserved
        · <a href="{% url 'index' %}">Simon's Blog</a>
        · <a href="http://www.nibiedian.gov.cn" target="_blank">XICP备XXXXXXXX号</a> 版权所有 © Simon
    </div>
</footer>
<script src="{% static "js/bundle.js" %}"></script>
<script type="text/javascript" src="{% static "js/view-history.js" %}"></script>
<script type='text/javascript' src="{% static "js/push.js" %}"></script>
<script type='text/javascript' src='{% static "js/jquery.min.js" %}'></script>
<script type='text/javascript' src='{% static "js/bootstrap.min.js" %}'></script>
<script type='text/javascript' src='{% static "js/raxus-slider.min.js" %}'></script>
<script type='text/javascript' src='{% static "js/loader.js" %}'></script>
<script type='text/javascript' src='{% static "js/bj-lazy-load.min.js" %}'></script>
<script type='text/javascript' src='{% static "js/os.js" %}'></script>
<script type="text/javascript" src='{% static "js/trackLine.js" %}'></script>
<script type="text/javascript" src="{% static "js/mouseClick.js"%}"></script>
<script type="text/javascript">
    var message_Path = "{% static "live2d/"%}"
    var home_Path = '127.0.0.1/'
</script>
<script type="text/javascript" src="{% static "live2d/js/live2d.js"%}"></script>
<script type="text/javascript" src="{% static "live2d/js/message.js"%}"></script>
<script type="text/javascript">
    loadlive2d("live2d", "{% static "live2d/model/haruto/haruto.model.json"%}");
</script>
<script type="text/javascript" src="{% static "js/progressIndicator.js"%}"></script>
<script type="text/javascript" src="{% static "js/back-top.js"%}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="main-container" class="container clearfix" style="opacity: 0.9">
        <section class="post-left">
            <div class="row">
                <!-- /banner图 -->
{#                <div class="col-md-6">#}
{#                    <div id="featured" class="raxus-slider" data-autoplay="3000" data-keypress="false"#}
{#                         data-thumbnail="bottom">#}
{#                        <ul class="slider-relative" id="relative">#}
{#                            {% for b in banner %}#}
{#                                <li class="slide fix-width">#}
{#                                    <a href="{{ b.link_url }}" title="{{ b.text_info }}">#}
{#                                        <img src="{% url 'index' %}media/{{ b.img }}" srcset="{% url 'index' %}media/{{ b.img }}" alt="{{ b.text_info }}"#}
{#                                        class="wp-post-image" width="370" height="290"/>#}
{#                                    </a>#}
{#                                    <span class="text ani-left"><strong>{{ b.text_info }}</strong></span>#}
{#                                </li>#}
{#                            {% endfor %}#}
{#                    </div>#}
{##}
{#                </div>#}
                <!-- /banner图 -->

                <!-- 首页推荐 -->
{#                <div class="col-md-6">#}
{#                    <div class="hotread ">#}
{#                        <div class="title">推荐阅读</div>#}
{#                        {% for t in shouyetui %}#}
{#                            <div class="caption">#}
{#                                <h4><a href="{% url 'index' %}show-{{ t.id }}.html" title="{{ t.title }}"#}
{#                                rel="bookmark">{{ t.title }}</a></h4>#}
{#                                <p>{{ t.excerpt|truncatechars:"80" }}</p>#}
{#                            </div>#}
{#                        {% endfor %}#}
{##}
{#                    </div>#}
{#                </div>#}
                <!-- /今日头条 -->
            </div>
            <!-- /文章列表 -->
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title fl" style="border-color: #9a3d4e73">最新文章</h4>
                    <div class="fr"></div>
                </div>
                <div class="row">
                    {% for a in articles %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'index' %}show-{{ a.id }}.html" title="{{ a.title }}">
                                        {% if a.img == "" %}
                                            <img src="{% static "picture/default.png" %}"
                                             srcset="{% static "picture/default.png" %}"
                                             alt="{{ a.title }}" class="wp-post-image" width="240" height="160"/>
                                        {% else %}
                                            <img src="media/{{ a.img }}"
                                             srcset="media/{{ a.img }}"
                                             alt="{{ a.title }}" class="wp-post-image" width="240" height="160"/>
                                        {% endif %}
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'index' %}show-{{ a.id }}.html" target="_blank"
                                       title="{{ a.title }}">{{ a.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="{% url 'index' %}show-{{ a.id }}.html" target="_blank"
                                                                title="{{ a.title }}">{{ a.excerpt }}</a></p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'index' %}list-{{ a.category.id }}.html">{{ a.category.name }}</a></span>
                                    <time class="item"><i class="fa fa-clock-o"></i>{{ a.created_time|date:"Y年m月d日" }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <!-- /文章列表 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">
            {% include 'right.html' %}

        </aside>
        <div class="FriendLink hidden-xs clearfix">
            <div class="title"><h3>友情链接：</h3></div>
            <ul class="clears">
                {% for l in link %}
                    <li><a href="{{ l.linkurl }}" target="_blank">{{ l.name }}</a></li>
                {% endfor %}

            </ul>
        </div>
    </div>
{% endblock %}

templates/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> »
                <span class="current">{{ cname }} </span></div>
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title" style="border-color: #9a3d4e73">分类：{{ cname}}</h4>
                </div>
                <div class="row">
                    {% for list in list %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'index' %}show-{{ list.id }}.html" title="{{ list.title }}">
                                        {% if list.img == "" %}
                                            <img src="{% static "picture/default.png" %}"
                                             srcset="{% static "picture/default.png" %}"
                                             alt="{{ list.title }}" class="wp-post-image" width="240" height="160"/>
                                        {% else %}
                                            <img src="media/{{ list.img }}"
                                             srcset="media/{{ list.img }}"
                                             alt="{{ list.title }}" class="wp-post-image" width="240" height="160"/>
                                        {% endif %}
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'index' %}show-{{ list.id }}.html" target="_blank"
                                       title="{{ list.title }}">{{ list.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="{% url 'index' %}show-{{ list.id }}.html"
                                                                target="_blank"
                                                                title="{{ list.title }}">{{ list.excerpt }}</a></p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'index' %}list-{{ list.category_id }}.html">{{ list.category.name }}</a></span>
                                    <time class="item"><i
                                            class="fa fa-clock-o"></i>{{ list.created_time|date:"Y年m月d日" }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                    <div class="pagination">
                        <ul>
                            {% if list.has_previous %}
                            <li class="prev-page"><a href="?page={{ list.previous_page_number }}">上一页</a></li>
                            {% else %}
                             <li class="prev-page"></li>
                            {% endif %}


                                {% for num in list.paginator.page_range %}
                                    {% if num %}
                                        {% ifequal num list.number %}
                                            <li class="active"><span>{{ num }}</span></li>
                                        {% else %}
                                            <li><a href="?page={{ num }}">{{ num }}</a></li>
                                        {% endifequal %}
                                    {% else %}
                                        <li class="disabled"><span>...</span></li>
                                    {% endif %}
                                {% endfor %}


                                {% if list.has_next %}
                                    <li class="next-page"><a href="?page={{ list.next_page_number }}">下一页</a></li>
                                {% else %}
                                    <li class="next-page"></li>
                                {% endif %}
                        </ul>
                    </div>


                    <!-- /文章列表 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">
            </section></section>

            {% include 'right.html' %}

        </aside>
    </div>
{% endblock %}

templates/page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> » <span class="current">关于我</span>
            </div>
            <div class="post-main clearfix">
                <h1 class="post-title" style="border-color: #9a3d4e73">关于我</h1>
                <div class="post-con clearfix">
                    <div class="article-meta"><span class="item">2020-05-04</span></div>
                    <article class="article-content">
                        <p> 不知道会不会有人看到这段话。
                        </p>
                        <p>
                            西澳大学Computer Science 本科毕业生，目前在墨尔本大学读研。和本科不同的是，跑去读Data Science了。平时也没啥特别
                        的兴趣，和普通宅男差不多，看看番什么的。偶尔会弹弹吉他，最近有在画画，太菜了就不放p站了。</p>
                        <p>
                            创建这个网站的初衷：疫情原因延迟开学了，刚好是本科毕业的假期，闲来无事练练手，也正好预先留一个地方，整理学习笔记什么的。</p>
                        <p>虽然说这个网站的建立初衷是自用，但如果有帮到你的话，我会很开心。大家一起学习共勉</p>



                    </article>

                </div>

            </div>
            <!-- /文章 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">
            <!-- /关注我 -->
            <div class="post-right-item">
                <a href="https://github.com/JAVAN000B/Blog" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#95605c; float: right; color:#fff; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}  @keyframes octocat-wave{0%,100%{transform:rotate(0)} 20%,60%{transform:rotate(-25deg)} 40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}  .github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
                <h4 class="post-right-title" style="border-color: #9a3d4e73">关注我</h4>
                 <div class="wid-about">
                    <p>一 个 小 白</p>
                    <img src= '{% static "picture/weixinqr.jpg"%}' alt="微信二维码-Simon" width="160" height="160">
                </div>
                <div class="wid-about">
                    <p><strong>联系方式:</strong></p>
                    <p>QQ:335789877</p>
                    <p>Email：335789877@qq.com</p>
                </div>
            </div>

        </aside>
    </div>
    <!-- /主体 -->
    <!-- 底部 -->
{% endblock %}

templates/right.html
{% load static %}
<section class="widget post-right-item">
                <h4 class="post-right-title"style="border-color: #9a3d4e73">热门文章排行</h4>
                <ol class="hot-list">
                {% for h in hot %}
                    <li><a class="title" href="{% url 'index' %}show-{{ h.id }}.html" title="{{ h.title }}">{{ h.title }}</a></li>
                {% endfor %}
                </ol>
{#    <h4 class="post-right-title">热门推荐</h4>#}
{#    <ul class="post-hot clearfix">#}
{#        {% for k in rementui %}#}
{#            <li>#}
{#                <div class="img">#}
{#                <a href="{% url 'index' %}show-{{ k.id }}.html" title="{{ k.title }}">#}
{#                <img src="{% url 'index' %}media/{{ k.img }}"#}
{#                 srcset="{% url 'index' %}media/{{ k.img }}" alt="{{ k.title }}"#}
{#                    class="wp-post-image" width="120" height="80"/>#}
{#                </a>#}
{#                </div>#}
{#                <div class="text">#}
{#                <a href="{% url 'index' %}show-{{ k.id }}.html" title="{{ k.title }}"#}
{#                           target="_blank">{{ k.title }}</a>#}
{#                </div>#}
{#               </li>#}
{#        {% endfor %}#}
{##}
{#    </ul>#}
</section>

</section>
<section class="widget post-right-item"><h4 class="post-right-title"style="border-color: #9a3d4e73">所有标签</h4>
    <div class="tags">
        {% for tag in allTag %}
            <a class="title" href="{% url 'index' %}tag/{{ tag.name }}">{{ tag.name }}</a>
        {% endfor %}
    </div>
</section>
</section><!-- /关注我 -->
<div class="post-right-item">
    <a href="https://github.com/JAVAN000B/Blog" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#95605c; float: right; color:#fff; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}  @keyframes octocat-wave{0%,100%{transform:rotate(0)} 20%,60%{transform:rotate(-25deg)} 40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}  .github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

    <h4 class="post-right-title"style="border-color: #9a3d4e73">关注我</h4>
    <div class="wid-about">
        <p>萌新的学习旅程</p>
        <img src= '{% static "picture/weixinqr.jpg"%}' alt="微信二维码-Simon" width="160" height="160">
    </div>
    <div class="wid-about">
        <p><strong>联系方式:</strong></p>
        <p>QQ:335789877</p>
        <p>Email：335789877@qq.com</p>
    </div>
</div>

templates/show.html
{% extends "base.html" %}
{% block content %}
    <div class="progressIndicator fix-progress-bar" style="position:fixed;top:0;left:0;height:1ch;background-color:#5bc0de;"></div>
    <!-- /主体 -->
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> » <a
                href="{% url 'index' %}list-{{ show.category.id }}.html">{{ show.category.name }}</a> »
                <span class="current">正文</div>
            <div class="post-main clearfix">
                <h1 class="post-title" style="border-color: #9a3d4e73">{{ show.title }}</h1>
                <div class="post-con clearfix">
                    <div class="article-meta">
                        <span class="item">分类：<a href="{% url 'index' %}list-{{ show.category.id }}.html" rel="category tag">{{ show.category.name }}</a></span>
                        <span class="item">作者：{{ show.user }}</span>
                        <span class="item">浏览：{{ show.views }}</span>
                        <span class="item">{{ show.created_time }}</span>
                    </div>
                    <article class="article-content">
                        {{ show.body|safe }}
                    </article>

                    <div class="post-tag"><span class="fa fa-tags" aria-hidden="true"></span>标签：
                        {% for tag in show.tags.all %}
                            <a href="{% url 'index' %}tag/{{ tag.name }}" rel="tag">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <div>
                        <div><b>上一篇：</b>
                            {% if netx_blog %}
                                <a href="show-{{ netx_blog.pk }}.html" class="article-tag">{{ netx_blog }}</a>
                            {% else %}
                                没有了
                            {% endif %}
                        </div>
                        <div><b>下一篇：</b>
                            {% if previous_blog %}
                                <a href="show-{{ previous_blog.pk }}.html" class="article-tag">{{ previous_blog }}</a>
                            {% else %}
                                没有了
                            {% endif %}
                        </div>
                    </div>
                </div>

                            <div class="comment  hidden-xs">
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form
                            action="{% url 'comment:post_comment' sid %}"
                            method="POST"
                        >
                        {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言：
                                    </strong>
                                </label>
                                <textarea
                                    type="text"
                                    class="form-control"
                                    id="body"
                                    name="body"
                                    rows="2"></textarea>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="/accounts/github/login/">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}


                <!-- 显示评论 -->
                <h4>共有{{ comments.count }}条评论</h4>
                <div>
                    {% for comment in comments %}
                        <hr>
                        <p>
                            <strong style="color: pink">
                                {{ comment.CommentUser }}
                            </strong> 于
                            <span style="color: green">
                                {{ comment.created|date:"Y-m-d H:i:s" }}
                            </span> 时说：
                            {% if user.is_authenticated %}
                                {% if comment.CommentUser.id == user.id  %}
                                    <a style="float: right;color: crimson" href="{% url 'deletecomment:delete_comment' comment.id sid %}" >删除</a>
                                {% endif %}

                            {% endif %}
                        </p>
                        <pre style="font-family: inherit; font-size: 1em;">
                        {{ comment.body }}</pre>
                    {% endfor %}
                </div>


            </div>


            </div>
            <!-- /文章 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">
            </section></section>

            {% include 'right.html' %}

        </aside>

        </aside>
    </div>
    <!-- /主体 -->
{% endblock %}